### ISSUE TITLE
License error in pyfvm

### ISSUE THREAD

**Issue by shoubhaniknath** [meshpro/pyfvm#50]
I have installed pyfvm with pip, but while running a code, I am getting the following license error:

Error: Unable to find valid license for product ID 973948c2-ac9b-4a78-b37b-2adaafcf5523. 

Add a license with

    slim install <your-license>
 (KG_NOT_FOUND)

Can anybody point me to the correct license? Thanks!

**Comment by nschloe** [comment]
https://github.com/meshpro
